/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. */
package cn.zhuatech.lms.service;
import cn.zhuatech.lms.common.BusinessException; import cn.zhuatech.lms.dto.LmsDto.*; import cn.zhuatech.lms.model.*; import cn.zhuatech.lms.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class LmsService {
    private final LearningPlanRepository orders; private final LearningRecordRepository reports; private final CourseRepository course; private final AssessmentRepository assessments; private final CurrentUserService current;
    public LmsService(LearningPlanRepository orders,LearningRecordRepository reports,CourseRepository course,AssessmentRepository assessments,CurrentUserService current){this.orders=orders;this.reports=reports;this.course=course;this.assessments=assessments;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getAcademyCode();List<LearningPlan> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findByAcademyCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<LearningPlanView> learningPlans(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){LearningPlan order=orders.findById(id).orElseThrow(()->new BusinessException("学习任务不存在"));if(order.getStatus()==LearningPlan.Status.COMPLETED)throw new BusinessException("已完成任务不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("完成数量不能超过任务剩余数量");order.report(request.goodQty(),request.defectQty());reports.save(new LearningRecord(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getOrderNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<LearningPlan> list){int planned=list.stream().mapToInt(LearningPlan::getPlannedQty).sum(),done=list.stream().mapToInt(LearningPlan::getCompletedQty).sum(),defects=list.stream().mapToInt(LearningPlan::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("今日学习",String.format("%,d",planned),list.size()+" 张学习任务","blue"),new Metric("学习完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("结果合规率",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 项异常","warn"),new Metric("课程异常",course.countByStatus(Course.Status.ALARM)+"",assessments.countByResult(Assessment.Result.PENDING)+" 项待考核","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),course.findAllByOrderByCodeAsc().stream().map(e->new CourseView(e.getCode(),e.getName(),e.getAcademy().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),assessments.findTop10ByOrderByIdDesc().stream().map(i->new AssessmentView(i.getAssessmentNo(),i.getLearningPlan().getOrderNo(),i.getLearningPlan().getProductName(),i.getAssessmentType(),i.getAssessmentQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private LearningPlanView view(LearningPlan o){return new LearningPlanView(o.getId(),o.getOrderNo(),o.getProductCode(),o.getProductName(),o.getAcademy().getName(),o.getAcademy().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getBatchNo(),progress(o));}
    private int progress(LearningPlan o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
